name: Test, lint and fix code style

on: ["push", "pull_request"]

jobs:
  test:
    name: Run tests with PHP ${{ matrix.php-version }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        php-version: [7.4, 8.0, 8.1, 8.2]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: ~/.composer/cache/files
          key: composer-cache-${{ matrix.php }}-${{ hashFiles('composer.json') }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: Dependencies installation
        run: composer update --no-interaction --prefer-dist

      - name: Run PHPUnit
        run: composer test
  lint:
    name: Lint code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4

      - name: Dependencies installation
        run: composer update --no-interaction --prefer-dist

      - name: Run PHPStan
        run: composer stan

  fix-style:
    name: Fix code style
    runs-on: ubuntu-latest
    needs: [test, lint]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache style
        uses: actions/cache@v3
        with:
          path: .php-cs-fixer.cache
          key: ${{ runner.OS }}-${{ github.repository }}-phpcsfixer-${{ github.sha }}
          restore-keys: |
            ${{ runner.OS }}-${{ github.repository }}-phpcsfixer-

      - name: Run PHP CS Fixer
        uses: docker://oskarstark/php-cs-fixer-ga

      - name: Commit fixes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "style: fix code style"
