on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

name: Release SDK

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: php
          package-name: open-pix/php-sdk
          extra-files: |
            src/Client.php
